"""Constants for the Marstek integration."""

DOMAIN = "marstek"
DEFAULT_NAME = "Marstek Device"
DEFAULT_UPDATE_INTERVAL = 30

# Configuration keys
CONF_HOST = "host"
CONF_PORT = "port"
CONF_UPDATE_INTERVAL = "update_interval"

# Default UDP port for Marstek API
DEFAULT_UDP_PORT = 30000

# Device models
SUPPORTED_MODELS = ["Venus C", "Venus E", "Venus D"]

# API command IDs (for JSON-RPC)
API_COMMAND_ID = 1

# API Methods (from working implementation)
METHOD_GET_DEVICE = "Marstek.GetDevice"
METHOD_WIFI_STATUS = "Wifi.GetStatus"
METHOD_BLE_STATUS = "BLE.GetStatus"
METHOD_BATTERY_STATUS = "Bat.GetStatus"
METHOD_PV_STATUS = "PV.GetStatus"
METHOD_ES_STATUS = "ES.GetStatus"
METHOD_ES_MODE = "ES.GetMode"
METHOD_ES_SET_MODE = "ES.SetMode"
METHOD_EM_STATUS = "EM.GetStatus"

# Connection parameters
COMMAND_TIMEOUT = 5
COMMAND_MAX_ATTEMPTS = 3
COMMAND_BACKOFF_BASE = 0.5
COMMAND_BACKOFF_FACTOR = 2.0
COMMAND_BACKOFF_MAX = 8.0
COMMAND_BACKOFF_JITTER = 0.1
DISCOVERY_TIMEOUT = 9
DISCOVERY_BROADCAST_INTERVAL = 2.0

# Error codes
ERROR_METHOD_NOT_FOUND = -32601

ALL_API_METHODS = [
    METHOD_GET_DEVICE,
    METHOD_WIFI_STATUS,
    METHOD_BLE_STATUS,
    METHOD_BATTERY_STATUS,
    METHOD_PV_STATUS,
    METHOD_ES_STATUS,
    METHOD_ES_MODE,
    METHOD_ES_SET_MODE,
    METHOD_EM_STATUS,
]
